
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS course text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS year text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS institution text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS bio text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phone text DEFAULT NULL;
